name: "Check and build flake"
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lints:
    name: Build for x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check --all-systems
      - run: nix build
    name: Build for arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - run: nix build

